server:
  port: 3005

spring:
  application:
    name: lab-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:hms_db}
    username: ${DB_USER:hms_user}
    password: ${DB_PASS:hms_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[default_schema]": lab
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

nats:
  url: ${NATS_URL:nats://localhost:4222}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  buckets:
    lab-reports: hms-lab-reports

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
