server:
    port: 3002

spring:
    application:
        name: clinical-service
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:hms_db}
        username: ${DB_USER:hms_user}
        password: ${DB_PASS:hms_password}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
nats:
    url: ${NATS_URL:nats://localhost:4222}

minio:
    url: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: hms-scans

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                orm:
                    jdbc:
                        bind: TRACE
